# Generated by Django 4.2.3 on 2023-07-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='qualific',
            new_name='qualification',
        ),
    ]
